# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Videogram' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Videogram
pod 'SDWebImage', '~>3.7'
pod "youtube-ios-player-helper", "~> 0.1.4"
end
